# Generated by Django 4.0.4 on 2022-05-26 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('userp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventObj',
            fields=[
                ('event_username', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('descripations', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_public', models.BooleanField(default=False)),
                ('host', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userp.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SubEventObj',
            fields=[
                ('serial_subevent', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('descripations', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_offline', models.BooleanField(default=True)),
                ('guest_user', models.CharField(max_length=250)),
                ('in_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.eventobj')),
            ],
        ),
    ]
